
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 7;
  public static final int AND = 8;
  public static final int LT = 21;
  public static final int ELSE = 15;
  public static final int PLUS = 3;
  public static final int RPAREN = 17;
  public static final int SEMI = 9;
  public static final int WHILE = 13;
  public static final int NOT = 10;
  public static final int TRUE = 11;
  public static final int IF = 14;
  public static final int GT = 22;
  public static final int LPAREN = 16;
  public static final int LE = 20;
  public static final int INTLIT = 23;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int FALSE = 12;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 19;
  public static final int ASSIGN = 2;
  public static final int FOR = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "AND",
  "SEMI",
  "NOT",
  "TRUE",
  "FALSE",
  "WHILE",
  "IF",
  "ELSE",
  "LPAREN",
  "RPAREN",
  "FOR",
  "EQ",
  "LE",
  "LT",
  "GT",
  "INTLIT"
  };
}

